name: smilei
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - cmcrameri
  - scipy
  - matplotlib
  - opencv
  - yt
  - h5py
  - hatchling
  - pint
  - jupyter
  - notebook
